"""Storage keys are generated by TRACE, never by the client (docs/SECURITY.md §5)."""

from __future__ import annotations

import pytest

from app.ingestion.naming import safe_basename, storage_key


@pytest.mark.parametrize(
    ("supplied", "expected"),
    [
        ("sysmon.jsonl", "sysmon.jsonl"),
        ("../../../etc/passwd", "passwd"),
        ("..%2f..%2fetc/shadow", "shadow"),
        (r"C:\Users\jsmith\Desktop\evil.evtx", "evil.evtx"),
        ("/absolute/path/conn.log", "conn.log"),
        ("with space & symbols!.log", "with_space_symbols_.log"),
        ("", "artifact.bin"),
        (None, "artifact.bin"),
        ("...", "artifact.bin"),
    ],
)
def test_safe_basename(supplied, expected) -> None:
    assert safe_basename(supplied) == expected


def test_storage_key_cannot_be_escaped_by_the_filename() -> None:
    key = storage_key("default", "CASE-0001", "EVD-abc", "../../../etc/passwd")
    assert key == "default/CASE-0001/EVD-abc/passwd"
    assert ".." not in key


def test_storage_key_sanitises_every_segment() -> None:
    key = storage_key("../tenant", "CASE-0001", "EVD-abc", "f.log")
    assert key.startswith("tenant/")
