query CartValidationsGenerateRunInput {
  shop {
    localTime {
      date
    }
  }
  cart {
    buyerIdentity {
      customer {
        id
        limitedPurchases: metafield(namespace: "scale", key: "limited_purchases") {
          value
        }
      }
    }
    lines {
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          product {
            id
            title
            maxPerCustomer: metafield(namespace: "scale", key: "max_per_customer") {
              value
            }
            limitUntil: metafield(namespace: "scale", key: "limit_until") {
              value
            }
            requiresLogin: metafield(namespace: "scale", key: "limit_requires_login") {
              value
            }
          }
        }
      }
    }
  }
}
